apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    opentelemetry: enabled
  name: iot-device-mgmt
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
      - env:
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                containerName: iot-device-mgmt
                resource: limits.memory
          - name: RABBITMQ_HOST
            value: rabbitmq
        image: ghcr.io/diwise/iot-device-mgmt:changeme
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: iot-device-mgmt
        ports:
          - containerPort: 8080
            name: default-port
            protocol: TCP
          - containerPort: 8000
            name: control-port
            protocol: TCP
        startupProbe:
          httpGet:
            path: /healthz
            port: control-port
        readinessProbe:
          httpGet:
            path: /readyz
            port: control-port
        livenessProbe:
          httpGet:
            path: /livez
            port: control-port
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
          - name: conf-volume
            mountPath: /opt/diwise/config
            readOnly: true
      serviceAccountName: iot-device-mgmt
      volumes:
        - name: conf-volume
          configMap:
            name: dev-mgmt-cfg-cm
