apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-device-mgmt
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
      - env:
          - name: RABBITMQ_HOST
            value: rabbitmq
        image: ghcr.io/diwise/iot-device-mgmt:changeme
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: iot-device-mgmt
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
        volumeMounts:
          - name: conf-volume
            mountPath: /opt/diwise/config
            readOnly: true
          - name: conf-volume-data
            mountPath: /opt/diwise/config/data
            subPath: 30.devices.csv
            readOnly: true
      serviceAccountName: iot-device-mgmt
      volumes:
        - name: conf-volume-data
          configMap:
            name: known-devices-cm
        - name: conf-volume
          configMap:
            name: dev-mgmt-cfg-cm
